apiVersion: v1
kind: Service
metadata:
  name: {{ include "ejabberd.fullname" . }}
  labels:
    {{- include "ejabberd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3478
      targetPort: xmpp-3478
      protocol: TCP
      name: xmpp-3478
    - port: 3478
      targetPort: xmpp-3478-udp
      protocol: UDP
      name: xmpp-3478-udp
    - port: 5222
      targetPort: xmpp-c2s
      protocol: TCP
      name: xmpp-c2s
    - port: 5223
      targetPort: xmpp-c2s-tls
      protocol: TCP
      name: xmpp-c2s-tls
    - port: 5269
      targetPort: xmpp-s2s
      protocol: TCP
      name: xmpp-s2s
    - port: 5347
      targetPort: int-slidge
      protocol: TCP
      name: int-slidge
    - port: 5349
      targetPort: xmpp-5349-tls
      protocol: TCP
      name: xmpp-5349-tls
    - port: 5443
      targetPort: http
      protocol: TCP
      name: http
    - port: 5280
      targetPort: xmpp-admin
      protocol: TCP
      name: xmpp-admin
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
    - port: 50000
      targetPort: xmpp-turn-50000
      protocol: TCP
      name: xmpp-turn-50000
    - port: 50001
      targetPort: xmpp-turn-50001
      protocol: TCP
      name: xmpp-turn-50001
    - port: 50002
      targetPort: xmpp-turn-50002
      protocol: TCP
      name: xmpp-turn-50002
    - port: 50003
      targetPort: xmpp-turn-50003
      protocol: TCP
      name: xmpp-turn-50003
    - port: 50004
      targetPort: xmpp-turn-50004
      protocol: TCP
      name: xmpp-turn-50004
    - port: 50005
      targetPort: xmpp-turn-50005
      protocol: TCP
      name: xmpp-turn-50005
    - port: 50006
      targetPort: xmpp-turn-50006
      protocol: TCP
      name: xmpp-turn-50006
    - port: 50007
      targetPort: xmpp-turn-50007
      protocol: TCP
      name: xmpp-turn-50007
    - port: 50008
      targetPort: xmpp-turn-50008
      protocol: TCP
      name: xmpp-turn-50008
    - port: 50009
      targetPort: xmpp-turn-50009
      protocol: TCP
      name: xmpp-turn-50009
    - port: 50010
      targetPort: xmpp-turn-50010
      protocol: TCP
      name: xmpp-turn-50010
  selector:
    {{- include "ejabberd.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ejabberd
