apiVersion: v1
kind: Service
metadata:
  name: {{ include "ejabberd.fullname" . }}
  labels:
    {{- include "ejabberd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3478
      targetPort: xmpp-3478
      protocol: TCP
      name: xmpp-3478
    - port: 3478
      targetPort: xmpp-3478-udp
      protocol: UDP
      name: xmpp-3478-udp
    - port: 5222
      targetPort: xmpp-c2s
      protocol: TCP
      name: xmpp-c2s
    - port: 5223
      targetPort: xmpp-c2s-tls
      protocol: TCP
      name: xmpp-c2s-tls
    - port: 5269
      targetPort: xmpp-s2s
      protocol: TCP
      name: xmpp-s2s
    - port: 5347
      targetPort: int-slidge
      protocol: TCP
      name: int-slidge
    - port: 5349
      targetPort: xmpp-5349-tls
      protocol: TCP
      name: xmpp-5349-tls
    - port: 5443
      targetPort: http
      protocol: TCP
      name: http
    - port: 5280
      targetPort: http-admin
      protocol: TCP
      name: http-admin
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    {{- include "ejabberd.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ejabberd
